-- 2026-08-03 出版社正名合併第三批(全庫變體掃描 645 對 → 人工判讀)。
-- 併入原則:同機構之全稱/簡稱/店碼(-T002 等)/(其它)(新樓)等後綴/公司型後綴變體。
-- 不併(留待內容側/階段三):聯合出版(頓號、斜線)、神學院/醫院/堂會/分會/研究中心等
--   不同機構、名稱過泛無法判定者(世界/生命/星/知/希望/天糧/真光/雅各/活石/綠洲 等)
--   → 未併清單見 docs/publisher-variants-kept-2026-08-03.md。
-- 前置:需先跑 2026-08-03_publisher_canonical_v2.sql(canonical 欄位已於 2026-07-16 建立)。
-- 回滾:UPDATE publishers SET canonical_id = NULL WHERE publisher_id IN (下列所有 IN 清單之 id);

UPDATE publishers SET canonical_id = 2748 WHERE publisher_id IN (4650, 4720);  -- 校園書房 ← 校園書房(其它) / 校園
UPDATE publishers SET canonical_id = 2275 WHERE publisher_id IN (4640);  -- 天恩出版社 ← 天恩出版社(其它)
UPDATE publishers SET canonical_id = 2810 WHERE publisher_id IN (4543, 4642, 4691);  -- 道聲 ← 道聲出版社(其他) / 道聲(其他) / 道聲影音綠標
UPDATE publishers SET canonical_id = 2757 WHERE publisher_id IN (3133, 2671, 4330, 4596, 4635);  -- 以琳書房 ← 以琳 / 以琳音樂產品 / 以琳出版社 / 以琳書房編譯小組 / 以琳書房(其它)
UPDATE publishers SET canonical_id = 2303 WHERE publisher_id IN (4699, 4631, 4779);  -- 中國主日學協會 ← 中國主日學(其它) / 中國主日學 / 中國主日學協會-發行部
UPDATE publishers SET canonical_id = 2287 WHERE publisher_id IN (4436);  -- 宣道 ← 宣道出版
UPDATE publishers SET canonical_id = 2817 WHERE publisher_id IN (4419);  -- 天道書樓 ← 天道書樓有限公司
UPDATE publishers SET canonical_id = 2755 WHERE publisher_id IN (4388, 4684, 4519);  -- 橄欖 ← 橄欖文化事業基金會 / 橄欖其它 / 橄欖出版社
UPDATE publishers SET canonical_id = 2768 WHERE publisher_id IN (4622, 4685);  -- 宇宙光 ← 宇宙光其它 / 宇宙光(其它)
UPDATE publishers SET canonical_id = 2763 WHERE publisher_id IN (4261);  -- 光啟文化 ← 光啟
UPDATE publishers SET canonical_id = 2839 WHERE publisher_id IN (4676, 3062, 3015);  -- 福音證主協會 ← 福音證主(其它) / 福音證主 / 證主
UPDATE publishers SET canonical_id = 2249 WHERE publisher_id IN (4404, 4824, 4525);  -- 國際漢語聖經出版社有限公司 ← 國際漢語聖經協會 / 國際漢語聖經 / 國際漢語聖經出版社
UPDATE publishers SET canonical_id = 2300 WHERE publisher_id IN (4538);  -- 台灣福音書房 ← 台灣福音書房-T002
UPDATE publishers SET canonical_id = 2270 WHERE publisher_id IN (4432, 4534);  -- 靈糧堂 ← 靈糧堂(台北靈糧堂發行組) / 靈糧堂(其它)
UPDATE publishers SET canonical_id = 2245 WHERE publisher_id IN (4439, 4816, 4828);  -- 聖經公會 ← 聖經公會出版部 / 聖經公會其它 / 聖經公會出版部(其它)
UPDATE publishers SET canonical_id = 2760 WHERE publisher_id IN (4506);  -- 啟示 ← 啟示出版社
UPDATE publishers SET canonical_id = 3165 WHERE publisher_id IN (4527);  -- 張老師文化 ← 張老師文化出版社
UPDATE publishers SET canonical_id = 4393 WHERE publisher_id IN (2765);  -- 華神出版社 ← 華神
UPDATE publishers SET canonical_id = 4438 WHERE publisher_id IN (2383, 4722);  -- 雅歌出版社 ← 雅歌 / 雅歌出版
UPDATE publishers SET canonical_id = 2274 WHERE publisher_id IN (3192);  -- 信福出版社 ← 信福
UPDATE publishers SET canonical_id = 2789 WHERE publisher_id IN (4423, 4402);  -- 改革宗 ← 改革宗出版 / 改革宗出版社
UPDATE publishers SET canonical_id = 2247 WHERE publisher_id IN (4421);  -- 香港浸信會 ← 香港浸信會出版社
UPDATE publishers SET canonical_id = 2304 WHERE publisher_id IN (2856, 4441, 4392, 4663);  -- 使徒出版社 ← 使徒 / 使徒出版社有限公司 / 使徒出版 / 使徒出版社有限公司(其它)
UPDATE publishers SET canonical_id = 2747 WHERE publisher_id IN (3063);  -- 香港基督徒學生福音團契（FES） ← 香港基督徒學生福音團契
UPDATE publishers SET canonical_id = 2277 WHERE publisher_id IN (4637, 4061, 4537, 4617, 4694);  -- 永望文化事業 ← 永望文化事業有限公司 / 永望文化 / 永望出版社 / 永望 / 永望出版
UPDATE publishers SET canonical_id = 2448 WHERE publisher_id IN (4569, 4558);  -- 異象工場 ← 異象工場(其它) / 異象工場(約書亞樂團)
UPDATE publishers SET canonical_id = 2296 WHERE publisher_id IN (4318);  -- 海天書樓 ← 海天
UPDATE publishers SET canonical_id = 4385 WHERE publisher_id IN (4665);  -- 香港基督教文藝出版社 ← 香港基督教文藝
UPDATE publishers SET canonical_id = 2504 WHERE publisher_id IN (4411);  -- 彩虹愛家生命教育協會 ← 彩虹愛家
UPDATE publishers SET canonical_id = 2480 WHERE publisher_id IN (4480);  -- 救世傳播協會 ← 救世傳播協會(ORTV)
UPDATE publishers SET canonical_id = 2284 WHERE publisher_id IN (2793, 4386);  -- 真哪噠出版社 ← 真哪噠 / 真哪噠股份有限公司
UPDATE publishers SET canonical_id = 2402 WHERE publisher_id IN (2331, 4524, 3546, 4702);  -- 以斯拉 ← 以斯拉培訓網絡 / 以斯拉培訓網路 / 以斯拉出版 / 以斯拉(其它)
UPDATE publishers SET canonical_id = 2840 WHERE publisher_id IN (4395);  -- 上智 ← 上智文化
UPDATE publishers SET canonical_id = 2299 WHERE publisher_id IN (4520);  -- 浸宣出版社 ← 浸宣出版社(其它)
UPDATE publishers SET canonical_id = 2968 WHERE publisher_id IN (4481);  -- 種籽 ← 種籽出版
UPDATE publishers SET canonical_id = 2307 WHERE publisher_id IN (4739);  -- 德慧文化 ← 德慧文化圖書有限公司
UPDATE publishers SET canonical_id = 2978 WHERE publisher_id IN (3601);  -- 天窗 ← 天窗出版社
UPDATE publishers SET canonical_id = 2248 WHERE publisher_id IN (4460, 4732, 4721);  -- 環球聖經公會 ← 環球聖經出版社 / 環球聖經 / 環球聖經(其它)
UPDATE publishers SET canonical_id = 2333 WHERE publisher_id IN (2794, 4747, 3411);  -- 格子外面文化事業有限公司 ← 格子外面 / 格子外面(其他) / 格子外面文化
UPDATE publishers SET canonical_id = 2264 WHERE publisher_id IN (4401, 3437, 4514, 4801);  -- 人光出版社 ← 人光出版社(新樓) / 人光 / 人光其它 / 人光影音綠標
UPDATE publishers SET canonical_id = 2315 WHERE publisher_id IN (3649);  -- 中國信徒佈道會 ← 中國信徒佈道
UPDATE publishers SET canonical_id = 2741 WHERE publisher_id IN (2416);  -- 印象文字 Inpress ← 印象文字
UPDATE publishers SET canonical_id = 2969 WHERE publisher_id IN (2890);  -- 三聯書店 ← 三聯
UPDATE publishers SET canonical_id = 2367 WHERE publisher_id IN (4075);  -- 歸主 ← 歸主出版社
UPDATE publishers SET canonical_id = 2797 WHERE publisher_id IN (3262);  -- 大田 ← 大田出版
UPDATE publishers SET canonical_id = 2791 WHERE publisher_id IN (4736);  -- 台北靈糧堂 ← 台北靈糧堂發行組
UPDATE publishers SET canonical_id = 4487 WHERE publisher_id IN (4628);  -- 彩虹兒童 ← 彩虹兒童(其它)
UPDATE publishers SET canonical_id = 2260 WHERE publisher_id IN (2961);  -- 活道出版社 ← 活道
UPDATE publishers SET canonical_id = 2769 WHERE publisher_id IN (2342);  -- 極光 ← 極光創作有限公司
UPDATE publishers SET canonical_id = 4251 WHERE publisher_id IN (2378);  -- 美國活泉出版社 ← 美國活泉
UPDATE publishers SET canonical_id = 2883 WHERE publisher_id IN (4713, 3299);  -- 聯經 ← 聯經出版社 / 聯經出版
UPDATE publishers SET canonical_id = 2371 WHERE publisher_id IN (4474);  -- 香港道聲 ← 香港道聲出版社
UPDATE publishers SET canonical_id = 2779 WHERE publisher_id IN (2272, 4424);  -- 恩道 ← 恩道出版有限公司 / 恩道出版社
UPDATE publishers SET canonical_id = 3022 WHERE publisher_id IN (4030);  -- 牛津大學 ← 牛津大學出版社
UPDATE publishers SET canonical_id = 2750 WHERE publisher_id IN (2319);  -- 播道會文字部 ← 播道會
UPDATE publishers SET canonical_id = 2594 WHERE publisher_id IN (2914);  -- 讚美之泉 ← 讚美之泉視聽文化股份有限公司
UPDATE publishers SET canonical_id = 3515 WHERE publisher_id IN (2278);  -- 中福 ← 中福出版有限公司
UPDATE publishers SET canonical_id = 2780 WHERE publisher_id IN (2341);  -- 保羅文化 ← 保羅文化出版社
UPDATE publishers SET canonical_id = 3340 WHERE publisher_id IN (2281, 4448);  -- 拾珍 ← 拾珍出版社 / 拾珍出版
UPDATE publishers SET canonical_id = 2366 WHERE publisher_id IN (4429);  -- 希望之聲 ← 希望之聲文化
UPDATE publishers SET canonical_id = 2829 WHERE publisher_id IN (3731);  -- 心靈工坊 ← 心靈工坊文化
UPDATE publishers SET canonical_id = 2744 WHERE publisher_id IN (4159, 2357);  -- 明風 ← 明風出版社 / 明風出版
UPDATE publishers SET canonical_id = 2311 WHERE publisher_id IN (4708);  -- 基稻田 ← 基稻田出版社
UPDATE publishers SET canonical_id = 2759 WHERE publisher_id IN (3237, 4516, 3140);  -- 皇冠 ← 皇冠出版社 / 皇冠文化 / 皇冠文化出版
UPDATE publishers SET canonical_id = 2334 WHERE publisher_id IN (4706);  -- 漢語基督教文化研究所 ← 漢語基督教
UPDATE publishers SET canonical_id = 2787 WHERE publisher_id IN (4760);  -- 木馬文化 ← 木馬
UPDATE publishers SET canonical_id = 2778 WHERE publisher_id IN (3359);  -- 究竟 ← 究竟出版社
UPDATE publishers SET canonical_id = 2819 WHERE publisher_id IN (2987);  -- 麥田 ← 麥田出版
UPDATE publishers SET canonical_id = 3028 WHERE publisher_id IN (3124, 3032);  -- 立緒文化 ← 立緒文化事業 / 立緒
UPDATE publishers SET canonical_id = 3084 WHERE publisher_id IN (4717);  -- 格林文化 ← 格林文化-1G090
UPDATE publishers SET canonical_id = 2772 WHERE publisher_id IN (2884, 2854, 3525, 3395, 4666);  -- 時報文化 ← 時報出版 / 時報 / 時報文化出版 / 時報文化出版企業股份 / 時報文化出版公司
UPDATE publishers SET canonical_id = 3519 WHERE publisher_id IN (3486);  -- 宗教文化 ← 宗教文化出版社
UPDATE publishers SET canonical_id = 4428 WHERE publisher_id IN (4772);  -- 瑞瑪出版有限公司 ← 瑞瑪出版有限公司(其它)
UPDATE publishers SET canonical_id = 2982 WHERE publisher_id IN (3285, 3255);  -- 高寶 ← 高寶國際有限公司 / 高寶國際
UPDATE publishers SET canonical_id = 3071 WHERE publisher_id IN (4483, 3785);  -- 晨星 ← 晨星出版社 / 晨星出版
UPDATE publishers SET canonical_id = 2417 WHERE publisher_id IN (4467);  -- 傳愛家族 ← 傳愛家族傳播文化事業有限公司
UPDATE publishers SET canonical_id = 2427 WHERE publisher_id IN (4674, 4700);  -- 道風山基督教叢林 ← 道風山基督教 / 道風山
UPDATE publishers SET canonical_id = 2837 WHERE publisher_id IN (2397, 3866, 4414);  -- 主流 ← 主流出版社有限公司 / 主流文化 / 主流出版
UPDATE publishers SET canonical_id = 2818 WHERE publisher_id IN (3385);  -- 星火文化 ← 星火文化出版
UPDATE publishers SET canonical_id = 2770 WHERE publisher_id IN (3686);  -- 悅知文化 ← 悅知
UPDATE publishers SET canonical_id = 2967 WHERE publisher_id IN (3116);  -- 好讀 ← 好讀出版
UPDATE publishers SET canonical_id = 2566 WHERE publisher_id IN (4616, 4073);  -- 基石 ← 基石出版社 / 基石文化
UPDATE publishers SET canonical_id = 2324 WHERE publisher_id IN (4247);  -- 中華信義神學院 ← 中華信義神學院出版社
UPDATE publishers SET canonical_id = 3224 WHERE publisher_id IN (2626, 4808, 4355);  -- 文林 ← 文林出版 / 文林出版社 / 文林出版社有限公司
UPDATE publishers SET canonical_id = 2478 WHERE publisher_id IN (4677, 4328);  -- 中國神學研究院 ← 中國神學 / 中國神學硏究院
UPDATE publishers SET canonical_id = 2369 WHERE publisher_id IN (4741);  -- 士林靈糧堂 ← 士林靈糧堂-S5043
UPDATE publishers SET canonical_id = 3090 WHERE publisher_id IN (3861);  -- 野人 ← 野人文化
UPDATE publishers SET canonical_id = 2871 WHERE publisher_id IN (2479);  -- 迎欣 ← 迎欣有限公司
UPDATE publishers SET canonical_id = 3294 WHERE publisher_id IN (2280);  -- 真理基金會 ← 真理基金會有限公司
UPDATE publishers SET canonical_id = 2751 WHERE publisher_id IN (2952, 4689);  -- 五南 ← 五南圖書 / 五南圖書出版公司
UPDATE publishers SET canonical_id = 2827 WHERE publisher_id IN (2885, 4767);  -- 三采 ← 三采文化 / 三采文化集團
UPDATE publishers SET canonical_id = 2373 WHERE publisher_id IN (3096);  -- GOOD TV好消息衛星電視台 ← Good TV
UPDATE publishers SET canonical_id = 2862 WHERE publisher_id IN (2986);  -- 圓神 ← 圓神出版社
UPDATE publishers SET canonical_id = 2377 WHERE publisher_id IN (3495);  -- 錫安堂出版社 ← 錫安堂
UPDATE publishers SET canonical_id = 2874 WHERE publisher_id IN (2975);  -- 中文大學 ← 中文大學出版社
UPDATE publishers SET canonical_id = 2845 WHERE publisher_id IN (3716);  -- 寶瓶文化 ← 寶瓶
UPDATE publishers SET canonical_id = 2822 WHERE publisher_id IN (2502);  -- 高接觸 ← 高接觸有限公司
UPDATE publishers SET canonical_id = 2766 WHERE publisher_id IN (3613);  -- 大好書屋 ← 大好
UPDATE publishers SET canonical_id = 2381 WHERE publisher_id IN (4458);  -- 歸正 ← 歸正出版社
UPDATE publishers SET canonical_id = 2330 WHERE publisher_id IN (4444);  -- 友友文化 ← 友友文化事業有限公司
UPDATE publishers SET canonical_id = 4638 WHERE publisher_id IN (4606, 4445);  -- 華宣 ← 華宣其他 / 華宣出版有限公司
UPDATE publishers SET canonical_id = 2849 WHERE publisher_id IN (4582);  -- 漫遊者文化 ← 漫遊者
UPDATE publishers SET canonical_id = 3481 WHERE publisher_id IN (4719);  -- 美國福音證主協會 ← 美國福音證主
UPDATE publishers SET canonical_id = 2984 WHERE publisher_id IN (2273);  -- 中華三一出版 ← 中華三一
UPDATE publishers SET canonical_id = 2308 WHERE publisher_id IN (4626);  -- 時兆文化 ← 時兆文化雜誌社
UPDATE publishers SET canonical_id = 3243 WHERE publisher_id IN (3836);  -- 心理 ← 心理出版社
UPDATE publishers SET canonical_id = 3379 WHERE publisher_id IN (2386);  -- 美國榮主 ← 美國榮主出版社
UPDATE publishers SET canonical_id = 3288 WHERE publisher_id IN (2359);  -- 主恩 ← 主恩出版社
UPDATE publishers SET canonical_id = 2349 WHERE publisher_id IN (4426);  -- 高示 ← 高示出版
UPDATE publishers SET canonical_id = 3598 WHERE publisher_id IN (2392);  -- 提比哩亞 ← 提比哩亞出版社
UPDATE publishers SET canonical_id = 2358 WHERE publisher_id IN (3162);  -- 經典傳承出版有限公司 ← 經典傳承
UPDATE publishers SET canonical_id = 4607 WHERE publisher_id IN (3650, 4611, 4778);  -- 慕主先鋒 ← 慕主先鋒傳播事工 / 慕主先峰傳播事工 / 慕主先峰傳播事工-B072
UPDATE publishers SET canonical_id = 4459 WHERE publisher_id IN (2663);  -- 上游出版社 ← 上游
UPDATE publishers SET canonical_id = 2384 WHERE publisher_id IN (4513);  -- 士林錫安堂 ← 士林錫安堂書房出版社
UPDATE publishers SET canonical_id = 2390 WHERE publisher_id IN (4690);  -- 生命流出版社 ← 生命流
UPDATE publishers SET canonical_id = 2415 WHERE publisher_id IN (4672);  -- 基督徒出版社 ← 基督徒出版
UPDATE publishers SET canonical_id = 2661 WHERE publisher_id IN (4453, 2446, 4391, 4775);  -- 飛鷹 ← 飛鷹出版社 / 飛鷹出版社(新店行道會) / 飛鷹出版 / 飛鷹出版-F6076
UPDATE publishers SET canonical_id = 3223 WHERE publisher_id IN (3046);  -- 先覺 ← 先覺出版
UPDATE publishers SET canonical_id = 4627 WHERE publisher_id IN (2525);  -- 基文社(其它) ← 基文社
UPDATE publishers SET canonical_id = 2312 WHERE publisher_id IN (2920, 4629, 4471, 4430, 4648, 3954);  -- 榮益出版有限公司 ← 榮益 / 榮益出版社 / 榮益印刷 / 榮益出版 / 榮益-K050 / 榮益印刷事業
UPDATE publishers SET canonical_id = 2933 WHERE publisher_id IN (2985);  -- 如果 ← 如果出版
UPDATE publishers SET canonical_id = 2828 WHERE publisher_id IN (3122);  -- 蜂鳥 ← 蜂鳥出版
UPDATE publishers SET canonical_id = 4366 WHERE publisher_id IN (2575);  -- 基石音樂有限公司 ← 基石音樂
UPDATE publishers SET canonical_id = 2253 WHERE publisher_id IN (2965);  -- 方舟機構有限公司 ← 方舟機構
UPDATE publishers SET canonical_id = 3626 WHERE publisher_id IN (4288, 4279);  -- 卓越使團 ← 卓越書樓 / 卓越
UPDATE publishers SET canonical_id = 3568 WHERE publisher_id IN (4455, 2945, 4693, 4621);  -- 中國學園傳道會 ← 中國學園傳道會出版部 / 學園傳道會 / 學園 / 中國學園傳道會出版部(其它)
UPDATE publishers SET canonical_id = 3174 WHERE publisher_id IN (4738);  -- 八旗文化 ← 八旗文化(讀書共和國)
UPDATE publishers SET canonical_id = 2966 WHERE publisher_id IN (3520);  -- 明窗 ← 明窗出版社
UPDATE publishers SET canonical_id = 3120 WHERE publisher_id IN (3123);  -- 臉譜 ← 臉譜出版
UPDATE publishers SET canonical_id = 2640 WHERE publisher_id IN (4707, 4655);  -- 白象文化 ← 白象文化事業有限公司 / 白象
UPDATE publishers SET canonical_id = 3518 WHERE publisher_id IN (2648);  -- 全心 ← 全心出版社
UPDATE publishers SET canonical_id = 3091 WHERE publisher_id IN (3952);  -- 左岸文化 ← 左岸
UPDATE publishers SET canonical_id = 3171 WHERE publisher_id IN (4218);  -- 加拿大福音證主協會 ← 加拿大福音
UPDATE publishers SET canonical_id = 4560 WHERE publisher_id IN (3301, 4809, 2603);  -- 希伯崙股份有限公司 ← 希伯崙 / 希伯崙有限公司 / 希伯崙企業股份有
UPDATE publishers SET canonical_id = 2382 WHERE publisher_id IN (3117);  -- 迦密文化事業有限公司 ← 迦密文化
UPDATE publishers SET canonical_id = 2983 WHERE publisher_id IN (2486);  -- 南神 ← 南神出版社
UPDATE publishers SET canonical_id = 3719 WHERE publisher_id IN (4176);  -- 九歌 ← 九歌出版社
UPDATE publishers SET canonical_id = 2291 WHERE publisher_id IN (4678);  -- 恩光 ← 恩光出版社
UPDATE publishers SET canonical_id = 3557 WHERE publisher_id IN (2387);  -- 金燈臺 ← 金燈臺出版社
UPDATE publishers SET canonical_id = 2861 WHERE publisher_id IN (4475);  -- 太雅 ← 太雅出版社
UPDATE publishers SET canonical_id = 2654 WHERE publisher_id IN (4673);  -- 創世記設計製作 ← 創世記
UPDATE publishers SET canonical_id = 3147 WHERE publisher_id IN (3354, 3189, 3184);  -- 臺灣商務印書館 ← 台灣商務印書館 / 台灣商務 / 臺灣商務
UPDATE publishers SET canonical_id = 2423 WHERE publisher_id IN (3603);  -- 青橄欖出版社 ← 青橄欖
UPDATE publishers SET canonical_id = 2286 WHERE publisher_id IN (3976, 2435, 3492);  -- 天人社 ← 基督教天人社 / 天人 / 基督教天人
UPDATE publishers SET canonical_id = 2543 WHERE publisher_id IN (4243);  -- 學生福音團契出版社 ← 學生福音團契
UPDATE publishers SET canonical_id = 2441 WHERE publisher_id IN (3048, 4785);  -- 亞洲歸主 ← 亞洲歸主協會 / 亞洲歸主協會-Y002
UPDATE publishers SET canonical_id = 4212 WHERE publisher_id IN (3248);  -- 小樹苗教育 ← 小樹苗
UPDATE publishers SET canonical_id = 3534 WHERE publisher_id IN (2545);  -- 聞道 ← 聞道出版社
UPDATE publishers SET canonical_id = 2938 WHERE publisher_id IN (4725);  -- 和撒那文化事業基金會 ← 和撒那文化事業基金會-T039
UPDATE publishers SET canonical_id = 3766 WHERE publisher_id IN (2408);  -- 恩谷 ← 恩谷出版社
UPDATE publishers SET canonical_id = 3616 WHERE publisher_id IN (3271);  -- 新手父母出版 ← 新手父母
UPDATE publishers SET canonical_id = 3039 WHERE publisher_id IN (3360);  -- 上海三聯書店 ← 上海三聯
UPDATE publishers SET canonical_id = 3305 WHERE publisher_id IN (3771);  -- 真証傳播有限公司 ← 真証傳播
UPDATE publishers SET canonical_id = 3197 WHERE publisher_id IN (3216);  -- 非凡 ← 非凡出版
UPDATE publishers SET canonical_id = 4698 WHERE publisher_id IN (4038);  -- 便雅憫 ← 便雅憫設計製作公司
UPDATE publishers SET canonical_id = 2605 WHERE publisher_id IN (4591);  -- 森日禮小舖 ← 森日禮
UPDATE publishers SET canonical_id = 2853 WHERE publisher_id IN (2777);  -- 日出出版 ← 日出
UPDATE publishers SET canonical_id = 3489 WHERE publisher_id IN (2628, 3581);  -- Edit Workshop Company Ltd ← EDIT WORKSHOP / EDIT Workshop Publishing
UPDATE publishers SET canonical_id = 2477 WHERE publisher_id IN (3606);  -- 美國中信 ← 美國中信出版社
UPDATE publishers SET canonical_id = 2836 WHERE publisher_id IN (4703);  -- 信義宗神學院 ← 信義宗神學
UPDATE publishers SET canonical_id = 3211 WHERE publisher_id IN (2825);  -- 香港大學 ← 香港大學出版社
UPDATE publishers SET canonical_id = 3912 WHERE publisher_id IN (4661);  -- 根基 ← 根基出版有限公司
UPDATE publishers SET canonical_id = 2339 WHERE publisher_id IN (3342);  -- 末世先鋒事工 ← 末世先鋒
UPDATE publishers SET canonical_id = 3800 WHERE publisher_id IN (3642, 4087);  -- 上海人民 ← 上海人民出版社 / 上海人民出版
UPDATE publishers SET canonical_id = 3194 WHERE publisher_id IN (4457, 4539);  -- 王天佑 ← 王天佑 牧師-1W001 / 王天佑 牧師
UPDATE publishers SET canonical_id = 3106 WHERE publisher_id IN (4360);  -- 基督教角聲佈道團有限公司 ← 基督教角聲佈道團
UPDATE publishers SET canonical_id = 3578 WHERE publisher_id IN (3389);  -- 香港城市大學 ← 香港城市大學出版社
UPDATE publishers SET canonical_id = 2805 WHERE publisher_id IN (3170, 4571);  -- 三民書局 ← 三民 / 三民出版社
UPDATE publishers SET canonical_id = 3093 WHERE publisher_id IN (3296);  -- 大家 ← 大家出版社
UPDATE publishers SET canonical_id = 2869 WHERE publisher_id IN (2923);  -- 福音研經 ← 福音研經有限公司
UPDATE publishers SET canonical_id = 3009 WHERE publisher_id IN (3075);  -- 國立臺灣大學出版中心 ← 國立臺灣大學
UPDATE publishers SET canonical_id = 2798 WHERE publisher_id IN (2355);  -- 寶瓦 ← 寶瓦出版有限公司
UPDATE publishers SET canonical_id = 2656 WHERE publisher_id IN (4067);  -- 三一音樂出版社 ← 三一音樂
UPDATE publishers SET canonical_id = 2360 WHERE publisher_id IN (2784);  -- 帶路國際商貿 ← 帶路國際
UPDATE publishers SET canonical_id = 2463 WHERE publisher_id IN (3193, 3906);  -- 海外校園雜誌社 ← 海外校園機構 / 海外校園
UPDATE publishers SET canonical_id = 4469 WHERE publisher_id IN (2606);  -- 厚禮牛創意 ← 厚禮牛創意有限公司
UPDATE publishers SET canonical_id = 2939 WHERE publisher_id IN (3030);  -- 大牌 ← 大牌出版
UPDATE publishers SET canonical_id = 2776 WHERE publisher_id IN (3060);  -- 就係媒體 ← 就係媒體有限公司
UPDATE publishers SET canonical_id = 2531 WHERE publisher_id IN (2899);  -- 迦南翻譯出版社 ← 迦南翻譯
UPDATE publishers SET canonical_id = 3070 WHERE publisher_id IN (3572);  -- 世茂 ← 世茂出版
UPDATE publishers SET canonical_id = 4254 WHERE publisher_id IN (2263);  -- 活石福音書室 ← 活石福音書室有限公司
UPDATE publishers SET canonical_id = 2681 WHERE publisher_id IN (4083);  -- 有情天音樂出版社 ← 有情天音樂
UPDATE publishers SET canonical_id = 3038 WHERE publisher_id IN (2879, 3300);  -- 春天 ← 春天出版 / 春天出版社
UPDATE publishers SET canonical_id = 4482 WHERE publisher_id IN (4710, 4595);  -- 香港以琳 ← 香港以琳書房 / 香港以琳書房-E016
UPDATE publishers SET canonical_id = 3991 WHERE publisher_id IN (3656);  -- 揚智文化 ← 揚智
UPDATE publishers SET canonical_id = 2996 WHERE publisher_id IN (4696);  -- 遠足文化 ← 遠足文化-R1020
UPDATE publishers SET canonical_id = 3173 WHERE publisher_id IN (3455);  -- 廣場 ← 廣場出版
UPDATE publishers SET canonical_id = 4546 WHERE publisher_id IN (4003);  -- 瑞馬出版有限公司 ← 瑞馬
UPDATE publishers SET canonical_id = 2934 WHERE publisher_id IN (3392);  -- 網路與書 ← 網路與書出版
UPDATE publishers SET canonical_id = 4230 WHERE publisher_id IN (4206);  -- 桂冠 ← 桂冠圖書
UPDATE publishers SET canonical_id = 2440 WHERE publisher_id IN (3872);  -- 加爾文出版社 ← 加爾文
UPDATE publishers SET canonical_id = 2362 WHERE publisher_id IN (4332);  -- 中華歸主 ← 中華歸主協會
UPDATE publishers SET canonical_id = 2530 WHERE publisher_id IN (4025);  -- 真生命輔導傳道會 ← 真生命
UPDATE publishers SET canonical_id = 3470 WHERE publisher_id IN (4774);  -- 凡能 ← 凡能出版
UPDATE publishers SET canonical_id = 3217 WHERE publisher_id IN (2385);  -- 紐約雅歌 ← 紐約雅歌出版社
UPDATE publishers SET canonical_id = 3765 WHERE publisher_id IN (4603);  -- 基督國度使命團 ← 基督國度使命團CKM-G082
UPDATE publishers SET canonical_id = 2459 WHERE publisher_id IN (4091);  -- 永恩出版社 ← 永恩
UPDATE publishers SET canonical_id = 2782 WHERE publisher_id IN (3521);  -- 超媒體 ← 超媒體出版
UPDATE publishers SET canonical_id = 4744 WHERE publisher_id IN (3830);  -- 綠園出版社 ← 綠園
UPDATE publishers SET canonical_id = 3774 WHERE publisher_id IN (2565);  -- 靈石 ← 靈石出版社
UPDATE publishers SET canonical_id = 3674 WHERE publisher_id IN (4604);  -- 傳神基金會 ← 傳神
UPDATE publishers SET canonical_id = 2514 WHERE publisher_id IN (4740);  -- 青年使命團 ← 青年使命團-C4291
UPDATE publishers SET canonical_id = 3584 WHERE publisher_id IN (3728, 3738);  -- 行人 ← 行人文化實驗室 / 行人出版
UPDATE publishers SET canonical_id = 3289 WHERE publisher_id IN (3430);  -- 世潮 ← 世潮出版
UPDATE publishers SET canonical_id = 2716 WHERE publisher_id IN (2723);  -- 鼎漢企業有限公司 ← 鼎漢
UPDATE publishers SET canonical_id = 3472 WHERE publisher_id IN (4158);  -- 中國人民大學 ← 中國人民大學出版社
UPDATE publishers SET canonical_id = 2467 WHERE publisher_id IN (3025);  -- 普世佳音新媒體傳播機構 ← 普世佳音
UPDATE publishers SET canonical_id = 3903 WHERE publisher_id IN (3905);  -- 北京大學出版社 ← 北京大學
UPDATE publishers SET canonical_id = 4649 WHERE publisher_id IN (3817);  -- 天下遠見出版股份有限公司 ← 天下遠見
UPDATE publishers SET canonical_id = 4572 WHERE publisher_id IN (4556);  -- 大和書報圖書股份有限公司 ← 大和書報圖書股份有限公司(其它)
UPDATE publishers SET canonical_id = 2340 WHERE publisher_id IN (2876);  -- 葡萄紙 ← 葡萄紙文化
UPDATE publishers SET canonical_id = 3086 WHERE publisher_id IN (2551);  -- 矽谷基督徒聚會 ← 矽谷基督徒
UPDATE publishers SET canonical_id = 2447 WHERE publisher_id IN (3156, 4449);  -- 聖約出版社 ← 聖約 / 聖約出版
UPDATE publishers SET canonical_id = 3314 WHERE publisher_id IN (3592);  -- 生命之旅 ← 生命之旅基督教培育中心
UPDATE publishers SET canonical_id = 2666 WHERE publisher_id IN (4184);  -- 綠洲傳播文化事業有限公司 ← 綠洲傳播
UPDATE publishers SET canonical_id = 3796 WHERE publisher_id IN (3956);  -- 華夏 ← 華夏出版
UPDATE publishers SET canonical_id = 2585 WHERE publisher_id IN (4447, 3527);  -- 比遜河出版社 ← 比遜河出版 / 比遜河
UPDATE publishers SET canonical_id = 3691 WHERE publisher_id IN (2646);  -- Oiktos ← Oiktos Limited
UPDATE publishers SET canonical_id = 2736 WHERE publisher_id IN (4777);  -- 祥福文創 ← 祥福文創有限公司
UPDATE publishers SET canonical_id = 2533 WHERE publisher_id IN (4565, 4485);  -- 十字星球文創社 ← 十字星球-S0002 / 十字星球
UPDATE publishers SET canonical_id = 2251 WHERE publisher_id IN (3643);  -- MORRISON CHRISTIAN LITERATURE ← Morrison
UPDATE publishers SET canonical_id = 2276 WHERE publisher_id IN (2742);  -- 黃儀章 ← 黃儀章博士
UPDATE publishers SET canonical_id = 3163 WHERE publisher_id IN (2469);  -- 國際視野（亞洲） ← 國際視野(亞洲)有限公司
UPDATE publishers SET canonical_id = 3177 WHERE publisher_id IN (2625);  -- 愛傳協會 ← 愛傳
UPDATE publishers SET canonical_id = 4641 WHERE publisher_id IN (3767, 4764);  -- 基督環球宣道出版社 ← 基督環球宣道 / 基督環球宣道出版社(其它)
UPDATE publishers SET canonical_id = 3052 WHERE publisher_id IN (3238);  -- EveryONE Press ← Everyone Press Ltd
UPDATE publishers SET canonical_id = 4798 WHERE publisher_id IN (3270, 3537);  -- 小熊(讀書共和國) ← 小熊出版 / 小熊
UPDATE publishers SET canonical_id = 3755 WHERE publisher_id IN (3720);  -- 社會科學文獻出版社 ← 社會科學文獻
UPDATE publishers SET canonical_id = 2686 WHERE publisher_id IN (4312);  -- 神州傳播公司 ← 神州
UPDATE publishers SET canonical_id = 2405 WHERE publisher_id IN (4326);  -- 少年歸主 ← 少年歸主社
UPDATE publishers SET canonical_id = 3681 WHERE publisher_id IN (2815);  -- MMO Productions Co. Ltd ← MMO Productions
UPDATE publishers SET canonical_id = 3143 WHERE publisher_id IN (3000);  -- 教會關懷貧窮網絡有限公司 ← 教會關懷貧窮網絡
UPDATE publishers SET canonical_id = 3543 WHERE publisher_id IN (2400);  -- 探索 ← 探索文化
UPDATE publishers SET canonical_id = 4387 WHERE publisher_id IN (2590, 3135);  -- 反骨出版社 ← 反骨社 / 反骨
UPDATE publishers SET canonical_id = 3298 WHERE publisher_id IN (3351);  -- 奇光 ← 奇光出版
UPDATE publishers SET canonical_id = 2954 WHERE publisher_id IN (4462);  -- 遇見你 ← 遇見你有限公司
UPDATE publishers SET canonical_id = 3191 WHERE publisher_id IN (4811);  -- 台北真道教會 ← 台北真道教會-J011
UPDATE publishers SET canonical_id = 2738 WHERE publisher_id IN (4166);  -- 文揚 ← 文揚工坊製作中心
UPDATE publishers SET canonical_id = 2864 WHERE publisher_id IN (2980);  -- 創意市集 ← 創意市集．城邦文化
UPDATE publishers SET canonical_id = 2709 WHERE publisher_id IN (2806);  -- 馬可樓上有限公司 ← 馬可樓
UPDATE publishers SET canonical_id = 3619 WHERE publisher_id IN (4323);  -- 中國社會科學 ← 中國社會科學出版社
UPDATE publishers SET canonical_id = 2911 WHERE publisher_id IN (3965);  -- 合記 ← 合記圖書
UPDATE publishers SET canonical_id = 3067 WHERE publisher_id IN (2523);  -- 土地教育基金 ← 土地教育基金有限公司
UPDATE publishers SET canonical_id = 3001 WHERE publisher_id IN (3974);  -- 博雅 ← 博雅書屋
UPDATE publishers SET canonical_id = 3614 WHERE publisher_id IN (3608);  -- 團結 ← 團結出版社
UPDATE publishers SET canonical_id = 3958 WHERE publisher_id IN (3769);  -- 中央編譯 ← 中央編譯出版社
UPDATE publishers SET canonical_id = 2607 WHERE publisher_id IN (3808);  -- 國際四一八文化事業股份有限公司 ← 國際四一八文化
UPDATE publishers SET canonical_id = 3319 WHERE publisher_id IN (4681);  -- 利未支派事奉協會 ← 利未支派事奉協會-1L002
UPDATE publishers SET canonical_id = 2554 WHERE publisher_id IN (4435);  -- 愛的影響力 ← 愛的影響力 LOVEGO
UPDATE publishers SET canonical_id = 3555 WHERE publisher_id IN (4127);  -- 晨曦會 ← 晨曦
UPDATE publishers SET canonical_id = 3414 WHERE publisher_id IN (2379, 4322);  -- 東南亞神學院協會 ← 東南亞神學 / 東南亞神學教會協會
UPDATE publishers SET canonical_id = 2909 WHERE publisher_id IN (2458);  -- 基督權能福音基金會 ← 基督權能福音
UPDATE publishers SET canonical_id = 4454 WHERE publisher_id IN (3317);  -- 復興列國有限公司 ← 復興列國
UPDATE publishers SET canonical_id = 4246 WHERE publisher_id IN (3964);  -- 新雨 ← 新雨出版社
UPDATE publishers SET canonical_id = 2644 WHERE publisher_id IN (3564);  -- 那打素全人健康持續進修學院 ← 那打素全人健康持續進修學
UPDATE publishers SET canonical_id = 4045 WHERE publisher_id IN (4013);  -- 漢宇國際 ← 漢宇
UPDATE publishers SET canonical_id = 2677 WHERE publisher_id IN (4765);  -- 艾普數碼國際 ← 艾普數碼國際-6057
UPDATE publishers SET canonical_id = 4442 WHERE publisher_id IN (3396);  -- 拾光工作室有限公司 ← 拾光
UPDATE publishers SET canonical_id = 4011 WHERE publisher_id IN (2597);  -- 余德淳訓練機構 ← 余德淳訓練機構有限公司
UPDATE publishers SET canonical_id = 2584 WHERE publisher_id IN (4797);  -- 生命光福音事工 ← 生命光福音
UPDATE publishers SET canonical_id = 4564 WHERE publisher_id IN (4632);  -- 文笙書局 ← 文笙
UPDATE publishers SET canonical_id = 3579 WHERE publisher_id IN (4316);  -- 加略山 ← 加略山房
UPDATE publishers SET canonical_id = 2411 WHERE publisher_id IN (4711);  -- 復文 ← 復文書局
UPDATE publishers SET canonical_id = 2466 WHERE publisher_id IN (4530);  -- 力和博 ← 力和博創新
UPDATE publishers SET canonical_id = 2516 WHERE publisher_id IN (4634);  -- 國際事工差會 ← 國際事工
UPDATE publishers SET canonical_id = 4733 WHERE publisher_id IN (4652);  -- 吳國銘 ← 吳國銘-W030
UPDATE publishers SET canonical_id = 3594 WHERE publisher_id IN (4576);  -- 香港國度事奉中心 ← 香港國度事奉中心-E016
UPDATE publishers SET canonical_id = 4486 WHERE publisher_id IN (4578, 2569);  -- 同心國際 ← 同心國際-T0015 / 同心國際傳播股份有限公司
UPDATE publishers SET canonical_id = 3017 WHERE publisher_id IN (3304);  -- 春山 ← 春山出版
UPDATE publishers SET canonical_id = 3635 WHERE publisher_id IN (3083);  -- 巨流 ← 巨流圖書
UPDATE publishers SET canonical_id = 3021 WHERE publisher_id IN (2482);  -- 主榮歸正生活 ← 主榮歸正生活出版社
UPDATE publishers SET canonical_id = 2347 WHERE publisher_id IN (2988);  -- 那好牧人出版社 ← 那好牧人
UPDATE publishers SET canonical_id = 3776 WHERE publisher_id IN (4377);  -- 論盡神學 ← 論盡神學出版社有限公司
UPDATE publishers SET canonical_id = 4743 WHERE publisher_id IN (4742);  -- 精瑩企業有限公司 ← 精瑩
UPDATE publishers SET canonical_id = 4016 WHERE publisher_id IN (4758);  -- 英柏爾 ← 英柏爾全球領導力股份有限公司
UPDATE publishers SET canonical_id = 2963 WHERE publisher_id IN (4630);  -- 旌旗文化 ← 旌旗文化-G5101
UPDATE publishers SET canonical_id = 2783 WHERE publisher_id IN (4418);  -- Global Trust Partners ← Global Trust Partners台灣辦公室
UPDATE publishers SET canonical_id = 4297 WHERE publisher_id IN (2406);  -- 靈水 ← 靈水出版社
UPDATE publishers SET canonical_id = 4528 WHERE publisher_id IN (3258);  -- 麥粒出版社 ← 麥粒
UPDATE publishers SET canonical_id = 4614 WHERE publisher_id IN (4671);  -- SAM ← SAM-S013
UPDATE publishers SET canonical_id = 3468 WHERE publisher_id IN (4623);  -- 關爾嘉 ← 關爾嘉-1G080
UPDATE publishers SET canonical_id = 2532 WHERE publisher_id IN (3201);  -- 情緒導向治療學院(亞洲) ← 情緒導向治療學院
UPDATE publishers SET canonical_id = 4125 WHERE publisher_id IN (4597);  -- 基督徒三峽福音中心 ← 基督徒三峽福
UPDATE publishers SET canonical_id = 2630 WHERE publisher_id IN (2851);  -- 行走奇蹟創意有限公司 ← 行走奇蹟
UPDATE publishers SET canonical_id = 2638 WHERE publisher_id IN (3081);  -- 平和樂聯盟有限公司 ← 平和樂聯盟
UPDATE publishers SET canonical_id = 2337 WHERE publisher_id IN (4410);  -- 出色 ← 出色文化
UPDATE publishers SET canonical_id = 2586 WHERE publisher_id IN (4577);  -- 稻田 ← 稻田出版
UPDATE publishers SET canonical_id = 2637 WHERE publisher_id IN (4545);  -- 台南活水基督教會團隊 ← 台南活水基督教會
UPDATE publishers SET canonical_id = 3523 WHERE publisher_id IN (3984);  -- 思維出版社 ← 思維
UPDATE publishers SET canonical_id = 2616 WHERE publisher_id IN (4464, 4338);  -- 甘霖出版社 ← 甘霖出版 / 甘霖
UPDATE publishers SET canonical_id = 4756 WHERE publisher_id IN (4697);  -- 董少桓 ← 董少桓-3D001
UPDATE publishers SET canonical_id = 4734 WHERE publisher_id IN (4728);  -- 基督教資料中心 ← 基督教資料中心(其它)
UPDATE publishers SET canonical_id = 2512 WHERE publisher_id IN (3854);  -- CIMI宣德 ← CIMI
UPDATE publishers SET canonical_id = 4199 WHERE publisher_id IN (4245);  -- 新新聞文化 ← 新新聞文化事業
UPDATE publishers SET canonical_id = 3676 WHERE publisher_id IN (4042);  -- 意象文化 ← 意象文化（Eshine）
UPDATE publishers SET canonical_id = 2855 WHERE publisher_id IN (2548);  -- 國際王家服事團 ← 國際王家服事團(美國)
UPDATE publishers SET canonical_id = 4757 WHERE publisher_id IN (4712);  -- 楨彥/楨德圖書 ← 楨彥/楨德圖書-J6013
UPDATE publishers SET canonical_id = 3487 WHERE publisher_id IN (3745);  -- 加拿大華人宣道會聯會 ← 加拿大華人宣道會
UPDATE publishers SET canonical_id = 4790 WHERE publisher_id IN (4793);  -- 恩膏 ← 恩膏國際文化事業有限公司
UPDATE publishers SET canonical_id = 4746 WHERE publisher_id IN (4658);  -- 謝秋玉 ← 謝秋玉-S006
UPDATE publishers SET canonical_id = 2438 WHERE publisher_id IN (4285);  -- 角石出版社 ← 角石
UPDATE publishers SET canonical_id = 3884 WHERE publisher_id IN (3937);  -- 木棉樹 ← 木棉樹出版社
UPDATE publishers SET canonical_id = 4093 WHERE publisher_id IN (4157);  -- 廣西師範大學 ← 廣西師範大學出版社

-- ── 保險:避免自我指向、別名指向別名(鏈拉直)──────────────
UPDATE publishers SET canonical_id = NULL WHERE canonical_id = publisher_id;
UPDATE publishers p
  JOIN publishers c ON c.publisher_id = p.canonical_id AND c.canonical_id IS NOT NULL
   SET p.canonical_id = c.canonical_id;
UPDATE publishers p
  JOIN publishers c ON c.publisher_id = p.canonical_id AND c.canonical_id IS NOT NULL
   SET p.canonical_id = c.canonical_id;

-- ── 驗證 ─────────────────────────────────────────────────
-- 1) 不應有別名指向別名(應回 0):
-- SELECT COUNT(*) FROM publishers p JOIN publishers c ON c.publisher_id=p.canonical_id
--  WHERE c.canonical_id IS NOT NULL;
-- 2) 正名後出版社數(去重):
-- SELECT COUNT(DISTINCT COALESCE(canonical_id, publisher_id)) FROM publishers;
